movies_wishlist/main/routes.py
import requests
from movies_wishlist.constants import URL
from flask import Blueprint, render_template, request
from movies_wishlist.main.forms import SearchForm
from movies_wishlist.main.models import Movie, MovieDetail
from flask import current_app as app

main = Blueprint("main", __name__)


def filter_movies_with_no_images(movie_list):
    """Return movies with contains poster

    :param movie_list: list of movies.
    :return: list of filtered movies.
    """
    return [movie for movie in movie_list if movie.get("Poster") != "N/A"]


def get_movies(name):
    """Get the movies from OMDB API

    :param name: name of the movie.
    :return: list of filtered movies.
    """
    params = {"apikey": app.config.get("API_KEY")}
    params.update({"s": name})
    response = requests.get(URL, params=params)
    for movie in response.json().get("Search"):
        movie["Tag"] = name
    return filter_movies_with_no_images(response.json().get("Search"))


def get_movie_detail(id):
    """Get a single movie from OMDB API

    :param id: IMDB ID
    :return: single movie.
    """
    params = {"apikey": app.config.get("API_KEY")}
    params.update({"i": id})
    response = requests.get(URL, params=params)
    return response.json()


@main.route("/", methods=["POST", "GET"])
def index():
    """Return index.html.

    :return: index page.
    """
    form = SearchForm()
    return render_template("index.html", form=form)


@main.route("/search", methods=["POST", "GET"])
def search():
    """Search for specific movie.

    :return: search page with filtered movies.
    """
    if request.method == "POST":
        movies = Movie.objects(Tag=request.form["name"]).all()
        if len(movies) > 0:
            return render_template("index.html", movies=movies)
    filtered_movies = get_movies(request.form["name"])
    movie_instances = [Movie(**data) for data in filtered_movies]
    Movie.objects.insert(movie_instances, load_bulk=False)
    return render_template("search.html", movies=filtered_movies)


@main.route("/detail/<string:imdbID>", methods=["GET", "POST"])
def detail(imdbID):
    """Returns single movie deatails

    :param imdbID: IMDB ID.
    :return: detail oage with single movie.
    """
    movie = Movie.objects(imdbID=imdbID).first()
    details = MovieDetail.objects(Movie=movie).first()
    if details:
        return render_template("detail.html", movie=details)
    response = get_movie_detail(imdbID)
    details = MovieDetail(
        Movie=movie,
        Rated=response.get("Rated"),
        Released=response.get("Released"),
        Runtime=response.get("Runtime"),
        Genre=response.get("Genre"),
        Director=response.get("Director"),
        Writer=response.get("Writer"),
        Actors=response.get("Actors"),
        Plot=response.get("Plot"),
        Language=response.get("Language"),
        imdbRating=response.get("imdbRating"),
        imdbVotes=response.get("imdbVotes"),
    )
    details.save()
    return render_template("detail.html", movie=details)

movies_wishlist/user/routes.py
from flask import Blueprint, flash, render_template, request, redirect, session, url_for
from flask_login import login_user, current_user, logout_user

from movies_wishlist.main.models import Movie
from .models import User
from movies_wishlist.extensions import bcrypt
from movies_wishlist.user.forms import LoginForm, RegistrationForm

user = Blueprint("user", __name__)


def get_fav_movies(fav_movies_ids):
    """Get user fav movies.

    :param fav_movies: list of fav movies id's.
    :return: list of user fav movies.
    """
    movies = []
    for fav_movie in fav_movies_ids:
        movie = Movie.objects(imdbID=fav_movie).first()
        movies.append(movie)
    return movies


@user.route("/register/", methods=["GET", "POST"])
def register():
    """Register a user

    :return: register page and register a user
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=hashed_password,
        )
        user.save()
        flash("Your account has been created! You are now able to log in", "success")
        return redirect(url_for("user.login"))
    return render_template("register.html", title="Register", form=form)


@user.route("/login/", methods=["GET", "POST"])
def login():
    """Login a user

    :return: login page and login a user
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            session["_user_id"] = str(user._id)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.index"))
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("login.html", title="Login", form=form)


@user.route("/add_to_wishlist/", methods=["GET", "POST"])
def add_to_wishlist():
    """Add user movie to wishlist

    :return: index page after adding the movie in the wishlist
    """
    user = User.objects(_id=current_user._id).first()
    if request.form.get("imdbID") not in user.fav_movies:
        user.fav_movies.append(request.form["imdbID"])
        user.save(validate=False)
    flash("Movie successfully Added", "info")
    return redirect(url_for("main.index"))


@user.route("/remove_from_wishlist/", methods=["GET", "POST"])
def remove_from_wishlist():
    """Remove movie from user wishlist

    :return: index page after removing the movie in the wishlist
    """
    user = User.objects(_id=current_user._id).first()
    user.fav_movies.remove(request.form["imdbID"])
    user.save(validate=False)
    flash("Movie successfully Removed", "info")
    return redirect(url_for("main.index"))


@user.route("/wishlist/", methods=["GET", "POST"])
def wishlist():
    """Show wishlist.

    :return: wishlist page.
    """
    user = User.objects(_id=current_user._id).first()
    movies = get_fav_movies(user.fav_movies)
    return render_template("wishlist.html", movies=movies)


@user.route("/logout/")
def logout():
    """Logout a user

    :return: logout a user.
    """
    logout_user()
    return redirect(url_for("main.index"))

movies_wishlist/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Album example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <style>
            .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
            }

            @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
            }
        </style>
    </head>
    <body>
        <header>
            <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <!-- Container wrapper -->
          <div class="container">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="{{url_for('main.index')}}">Movie Wishlist</a>
        
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
              data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
              <i class="fas fa-bars text-light"></i>
            </button>
            
            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <!-- Right links -->
              <ul class="navbar-nav ms-auto d-flex flex-row mt-3 mt-lg-0">
                {% if current_user.is_authenticated %}
                <li class="nav-item text-center mx-2 mx-lg-1">
                  <span class="nav-link" >
                    {{current_user.username}}
                  </span>
                </li>
                <li class="nav-item text-center mx-2 mx-lg-1">
                  <a class="nav-link" href="{{ url_for('user.wishlist') }}">
                    Your Wishlist
                  </a>
                </li>
                <li class="nav-item text-center mx-2 mx-lg-1">
                  <a class="nav-link" href="{{ url_for('user.logout') }}">
                    Logout
                  </a>
                </li>
                {% else %}
                <li class="nav-item text-center mx-2 mx-lg-1">
                  <a class="nav-link" href="{{ url_for('user.login') }}">
                    Login
                  </a>
                </li>
                <li class="nav-item text-center mx-2 mx-lg-1">
                  <a class="nav-link" href="{{ url_for('user.register') }}">
                    Register
                  </a>
                </li>
                {% endif %}
              </ul>
              <!-- Right links -->
            <!-- Collapsible wrapper -->
          </div>
          <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
        </header>
        <main role="main" class="container">
          <div class="row">
            <div class="offset-md-2 col-md-8">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
              {% block content %}{% endblock %}
            </div>
          </div>
        </main>
        <script defer src="https://use.fontawesome.com/releases/v6.0.0/js/solid.js" integrity="sha384-IWq2srnodX6Z+US+NFdwALHXDvdogKkBx7sUMzfypASSeqsNzF+gAS48WnkPcYbf" crossorigin="anonymous"></script>
        <script defer src="https://use.fontawesome.com/releases/v6.0.0/js/fontawesome.js" integrity="sha384-pULjvYk4ZbCHxvgkOUhY3s6wbSkRp/9WHqh+NdM+FkmDQsdJeg2XyOHSEQ0AZlr4" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </body>
</html>

movies_wishlist/templates/detail.html
{% extends "base.html" %}
{% block content %}

<style>
body{
    background:#eee;
}


.product-content {
    border: 0.5px solid #dfe5e9;
    background: #fff
}


.product-content .product-image {
    background-color: #fff;
    display: block;
    min-height: 238px;
    overflow: hidden;
    position: relative
}

.product-content .product-deatil {
    border-bottom: 1px solid #dfe5e9;
    padding-bottom: 17px;
    padding-left: 16px;
    padding-top: 16px;
    position: relative;
    background: #fff
}

.product-content .product-deatil h5 a {
    color: #2f383d;
    font-size: 15px;
    line-height: 19px;
    text-decoration: none;
    padding-left: 0;
    margin-left: 0
}

.product-content .product-deatil h5 a span {
    color: #9aa7af;
    display: block;
    font-size: 13px
}

.product-content .product-deatil span.tag1 {
    border-radius: 50%;
    color: #fff;
    font-size: 15px;
    height: 50px;
    padding: 13px 0;
    position: absolute;
    right: 10px;
    text-align: center;
    top: 10px;
    width: 50px
}

.product-content .product-deatil span.sale {
    background-color: #21c2f8
}

.product-content .product-deatil span.discount {
    background-color: #71e134
}

.product-content .product-deatil span.hot {
    background-color: #fa9442
}

.product-content .description {
    font-size: 12.5px;
    line-height: 20px;
    padding: 10px 14px 16px 19px;
    background: #fff
}

.product-content .product-info {
    padding: 11px 15px 10px 15px
}

.product-content .product-info a.add-to-cart {
    color: #2f383d;
    font-size: 13px;
    padding-left: 16px
}

.product-content name.a {
    padding: 5px 10px;
    margin-left: 16px
}

.product-info.smart-form .btn {
    padding: 6px 12px;
    margin-left: 12px;
    margin-top: -10px
}

.product-entry .product-deatil {
    border-bottom: 1px solid #dfe5e9;
    padding-bottom: 17px;
    padding-left: 16px;
    padding-top: 16px;
    position: relative
}

.product-entry .product-deatil h5 a {
    color: #2f383d;
    font-size: 15px;
    line-height: 19px;
    text-decoration: none
}

.product-entry .product-deatil h5 a span {
    color: #9aa7af;
    display: block;
    font-size: 13px
}

.load-more-btn {
    background-color: #21c2f8;
    border-bottom: 2px solid #037ca5;
    border-radius: 2px;
    border-top: 2px solid #0cf;
    margin-top: 20px;
    padding: 9px 0;
    width: 100%
}

.product-info.smart-form .rating label {
    margin-top: 0
}

.product-wrap .product-image span.tag2 {
    position: absolute;
    top: 10px;
    right: 10px;
    width: 36px;
    height: 36px;
    border-radius: 50%;
    padding: 10px 0;
    color: #fff;
    font-size: 11px;
    text-align: center
}

.product-wrap .product-image span.sale {
    background-color: #57889c
}

.product-wrap .product-image span.hot {
    background-color: #a90329
}

.description-tabs {
    padding: 30px 0 5px!important
}

.description-tabs .tab-content {
    padding: 10px 0
}

.product-deatil {
    padding: 30px 30px 40px
}

.product-deatil hr+.description-tabs {
    padding: 0 0 5px!important
}

.product-deatil .carousel-control.left,
.product-deatil .carousel-control.right {
    background: none!important
}

.product-deatil .glyphicon {
    color: #3276b1
}

.product-deatil .product-image {
    border-right: none!important
}

.product-deatil .name {
    margin-top: 0;
    margin-bottom: 0
}

.product-deatil .name small {
    display: block
}

.product-deatil .name a {
    margin-left: 0
}

.product-deatil .fa-2x {
    font-size: 16px!important
}

.product-deatil .fa-2x>h5 {
    font-size: 12px;
    margin: 0
}

.product-deatil .fa-2x+a,
.product-deatil .fa-2x+a+a {
    font-size: 13px
}

@media only screen and (min-width:1024px) {
    .product-content div[class*=col-md-4] {
        padding-right: 0
    }
    .product-content div[class*=col-md-8] {
        padding: 0 13px 0 0
    }
    .product-wrap div[class*=col-md-5] {
        padding-right: 0
    }
    .product-wrap div[class*=col-md-7] {
        padding: 0 13px 0 0
    }
    .product-content .product-image {
        border-right: 1px solid #dfe5e9
    }
    .product-content .product-info {
        position: relative
    }
}

.message img.online {
    width:40px;
    height:40px;
}
</style>

<div class="container">
    <!-- product -->
    <div class="product-content product-wrap clearfix product-deatil">
        <div class="row">
            <div class="col-md-5 col-sm-12 col-xs-12">
                <div class="product-image">
                    <img src="{{movie.Movie.Poster}}" class="img-fluid"/>
                </div>
            </div>

            <div class="col-md-6 col-md-offset-1 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="name">{{movie.Movie.Title}}</h2>
                            <small><p><i>{{movie.Movie.Year}} . {{movie.Rated}} . {{movie.Runtime}}</i></p></small>
                    </div>
                    <div class="col-md-6">
                        <p><i class="fa-solid fa-star"></i>{{movie.imdbRating}}</p>
                        <p>{{movie.imdbVotes}}</p>
                    </div>
                </div>
                <span class="badge bg-secondary">{{movie.Genre}}</span>
                <hr />
                <p class="small">{{movie.Plot}}</p>
                <hr />
                <div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b>Director</b>&nbsp;&nbsp;{{movie.Director}}</li>
                        <li class="list-group-item"><b>Writer</b>&nbsp;&nbsp;{{movie.Writer}}</li>
                        <li class="list-group-item"><b>Cast</b>&nbsp;&nbsp;{{movie.Actors}}</li>
                      </ul>
                </div>
                <hr />
                <div class="col-sm-12 col-md-12">
                    {% if current_user.is_authenticated %}
                    <div class="btn-group pull-right">
                        {% if movie.Movie.imdbID not in current_user.fav_movies %}
                        <form action="{{url_for('user.add_to_wishlist')}}" method="POST">
                            <input type="hidden" id="imdbID" name="imdbID" value="{{movie.Movie.imdbID}}">
                            <input type="submit" value="Add to wishlist" class="btn btn-info">
                            {% else %}
                        </form>
                        <form action="{{url_for('user.remove_from_wishlist')}}" method="POST">
                            <input type="hidden" id="imdbID" name="imdbID" value="{{movie.Movie.imdbID}}">
                            <input type="submit" value="Remove from wishlist" class="btn btn-info">
                        </form>
                        {% endif %}
                    </div>
                    {% else %}
                    <small class="text-muted">
                        If you wish to add it in your wishlist, Sign In? <a class="ml-2" href="{{ url_for('user.login') }}">Sign In</a>
                    </small>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- end product -->
</div>


{% endblock %}

movies_wishlist/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="content-section mt-2">
    <form method="POST" action="{{url_for('main.search')}}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Search Movies and Series</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-success") }}
        </div>
    </form>
</div>
            
{% endblock %}

movies_wishlist/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section mt-2">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="#">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('user.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

movies_wishlist/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="content-section mt-2">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.first_name.label(class="form-control-label") }}
                {% if form.first_name.errors %}
                    {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.first_name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.first_name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.last_name.label(class="form-control-label") }}
                {% if form.last_name.errors %}
                    {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.last_name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.last_name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('user.login') }}">Sign In</a>
    </small>
</div>
{% endblock %}

movies_wishlist/templates/search.html
{% extends "base.html" %}
{% block content %}
<main>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for movie in movies %}
        <div class="col-md-3 d-flex align-items-stretch">
          <div class="card shadow-sm">
            <img src="{{movie.Poster}}" width=""/>
            <div class="card-body">
            <div class="content">
                <p class="txt4">Release Year: <b><i>{{movie.Year}}</i></b></p>
                <hp class="txt5">Title: <b><i>{{movie.Title}}</i></b></p>
            </div>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <form action="{{url_for('main.detail', imdbID=movie.imdbID )}}" method="POST">
                    <input class="btn btn-sm btn-outline-info" type="submit" name="detail_id" value="Read More" />
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
</main>
{% endblock %}

movies_wishlist/templates/wishlist.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for movie in movies %}
      <div class="col-md-3 d-flex align-items-stretch">
        <div class="card shadow-sm">
          <img src="{{movie.Poster}}" width=""/>
          <div class="card-body">
          <div class="content">
              <p class="txt4">Release Year: <b><i>{{movie.Year}}</i></b></p>
              <hp class="txt5">Title: <b><i>{{movie.Title}}</i></b></p>
          </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</main>
{% endblock %}